apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-api-read
  description: Payment api for gRPC
  tags:
   - payments
   - id:1001
spec:
  type: grpc
  lifecycle: production
  owner: team-b
  definition: |

    syntax = "proto3";

    option java_multiple_files = true;
    option java_package = "io.grpc.payment.read";
    option java_outer_classname = "Accounts";
    option objc_class_prefix = "HLW";

    package helloworld;

    // The greeting service definition.
    service GetAccounts {
      // Sends a greeting
      rpc GetBallance (ClientId) returns (BallanceReply) {}
    }

    // The request message containing the user's name.
    message ClientId {
      string id = 1;
    }

    // The response message containing the greetings
    message BallanceReply {
      string ballance = 1;
    }
